### ISSUE TITLE
Text channel and voice channel suddenly become uncached

### ISSUE THREAD

**Issue by Brainicism** [Brainicism/KMQ_Discord#1021]
```
2021-09-23T05:32:24.418Z [ERROR] - Cluster 1 | utils | Could not fetch text channel: 705870100879900745. err: 50001. msg: Missing Access
2021-09-23T05:32:24.635Z [ERROR] - Cluster 1 | utils | Could not fetch text channel: 705870100879900745. err: 50001. msg: Missing Access
2021-09-23T05:32:24.638Z [ERROR] - Cluster 1 | Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'voiceMembers' of undefined
      at getCurrentVoiceMembers (/home/kmq/prod/build/helpers/discord_utils.js:623:43)
      at getNumParticipants (/home/kmq/prod/build/helpers/discord_utils.js:631:12)
      at GameSession.multiguessDelayIsActive (/home/kmq/prod/build/structures/game_session.js:1020:70)
      at GameSession.<anonymous> (/home/kmq/prod/build/structures/game_session.js:386:43)
      at Generator.next (<anonymous>)
      at /home/kmq/prod/build/structures/game_session.js:27:71
      at new Promise (<anonymous>)
      at __awaiter (/home/kmq/prod/build/structures/game_session.js:23:12)
      at GameSession.startRound (/home/kmq/prod/build/structures/game_session.js:384:16)
      at GameSession.<anonymous> (/home/kmq/prod/build/structures/game_session.js:714:22)
} reason: TypeError: Cannot read property 'voiceMembers' of undefined
2021-09-23T05:32:24.639Z [ERROR] - Cluster 1 | unhandledRejection | Cluster Unhandled Rejection at: Reason: TypeError: Cannot read property 'voiceMembers' of undefined. Trace: TypeError: Cannot read property 'voiceMembers' of undefined
    at getCurrentVoiceMembers (/home/kmq/prod/build/helpers/discord_utils.js:623:43)
    at getNumParticipants (/home/kmq/prod/build/helpers/discord_utils.js:631:12)
    at GameSession.multiguessDelayIsActive (/home/kmq/prod/build/structures/game_session.js:1020:70)
    at GameSession.<anonymous> (/home/kmq/prod/build/structures/game_session.js:386:43)
    at Generator.next (<anonymous>)
    at /home/kmq/prod/build/structures/game_session.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/home/kmq/prod/build/structures/game_session.js:23:12)
    at GameSession.startRound (/home/kmq/prod/build/structures/game_session.js:384:16)
    at GameSession.<anonymous> (/home/kmq/prod/build/structures/game_session.js:714:22)
2021-09-23T05:32:24.675Z [ERROR] - Cluster 1 | utils | Error sending message, and channel not cached. textChannelID = 705870100879900745
```

**Comment by Brainicism** [comment]
Likely due to bot being kicked from server

**Comment by Brainicism** [comment]
This is due to the bot being kicked from a server
