### ISSUE TITLE
SongSelector.getUniqueSongCounter null reference exception

### ISSUE THREAD

**Issue by Brainicism** [Brainicism/KMQ_Discord#1301]
2022-04-18T06:09:56.925Z [ERROR] - Cluster 0 | unhandledRejection | Cluster Unhandled Rejection at: Reason: TypeError: Cannot read properties of null (reading 'songs'). Trace: TypeError: Cannot read properties of null (reading 'songs')
 at SongSelector.getUniqueSongCounter (/home/kmq/prod-2/build/structures/song_selector.js:39:62)
 at MusicSession.<anonymous> (/home/kmq/prod-2/build/structures/music_session.js:60:235)

**Comment by Brainicism** [comment]
Fixed by https://github.com/Brainicism/KMQ_Discord/commit/4d91c42ecd4980cdfdc2f1eb6e1887cba4ef9534
