### ISSUE TITLE
Error on playSong when user not in voice channel guesses correctly

### ISSUE THREAD

**Issue by Brainicism** [Brainicism/KMQ_Discord#150]
https://github.com/Brainicism/KMQ_Discord/blob/d32145513e34f9e9fc4bab3c1928cba0caa033c7/helpers/utils.js#L215
```
(node:29171) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'bitrate' of null
    at playSong (/home/brian/node/KMQ_Discord_dev/src/helpers/utils.js:215:31)
    at startGame (/home/brian/node/KMQ_Discord_dev/src/helpers/utils.js:29:9)
(node:29171) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by taahamahdi** [comment]
Haha, I'll take a look at that.
